name: kind-perf-e2e
on:
  push:
    branches: [main]
  workflow_run:
    workflows:
      - ApprovalComment
    types:
      - completed
  workflow_dispatch:
jobs:
  kind-perf-e2e:
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    permissions:
      issues: write
    strategy:
      fail-fast: false
      matrix:
        test:
          - name: "Drift Performance"
            focus: "Drift Performance"
          - name: "Host Name Spreading"
            focus: "Host Name Spreading Deployment Reg"
          - name: "Host Name Spreading XL"
            focus: "Host Name Spreading Deployment XL"
          - name: "Wide Deployments"
            focus: "Wide Deployments"
          - name: "Basic Scale Test"
            focus: "Basic Deployment"
          - name: "Do Not Disrupt Performance"
            focus: "Do Not Disrupt Performance Test"
          - name: "Provisioning"
            focus: "Provisioning"
          - name: "Self Anti-Affinity Deployment Interference"
            focus: "Self Anti-Affinity Deployment Interference"
    uses: ./.github/workflows/e2e.yaml
    with:
      suite: Performance
      focus: ${{ matrix.test.focus }}
      test_name: ${{ matrix.test.name }}
