name: presubmit
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  presubmit:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8sVersion: ["1.28.x", "1.29.x", "1.30.x", "1.31.x", "1.32.x", "1.33.x", "1.34.x"]
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: ./.github/actions/install-deps
      with:
        k8sVersion: ${{ matrix.k8sVersion }}
    - name: Enable the actionlint matcher
      run: echo "::add-matcher::.github/actionlint-matcher.json"
    - run: K8S_VERSION=${{ matrix.k8sVersion }} make presubmit
    - name: Send coverage
      # should only send converage once https://docs.coveralls.io/parallel-builds
      if: matrix.k8sVersion == '1.34.x'
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: go tool -modfile=go.tools.mod goveralls -coverprofile=coverage.out -service=github
