name: "Run Bench Test"

on:
  workflow_call:
    inputs:
      path:
        description: Path to the performance test
        required: true
        type: string
      runName:
        description: Name of the run, for the purpose of file naming and github comments
        required: true
        type: string
      githubSha:
        description: Sha of the github commit to check out
        required: true
        type: string
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.githubSha }}
      - name: Run Test
        id: test-run
        shell: bash
        run: |
          {
            cd ${{ inputs.path }}
            mkdir output
            go test -tags=test_performance -run=1 -bench=. -count=1 -cpuprofile output/cpu.out -memprofile output/mem.out > output/results.txt
            echo 'OUTPUT<<EOF'
            cat output/results.txt
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        id: artifact-upload
        with:
          name: ${{ inputs.runName }}
          path: ${{ inputs.path }}/output